DROP SEQUENCE COMROOM_SEQ;
DROP SEQUENCE COMBOARD_SEQ;
DROP SEQUENCE BOARDCOM_SEQ;
DROP TABLE COMROOM;
DROP TABLE COMBOARD;
DROP TABLE BOARDCOM;

CREATE SEQUENCE COMROOM_SEQ;
CREATE SEQUENCE COMBOARD_SEQ;
CREATE SEQUENCE BOARDCOM_SEQ;

-- CONSTRAINT WORKSPACE_PK PRIMARY KEY(WORKSPACE_NUM)
-- CONSTRAINT WORKSPACE_FK FOREIGN KEY(MEMBER_NUM) REFERENCES MEMBER(MEMBER_NUM) ON DELETE CASCADE ENABLE

CREATE TABLE COMROOM(
	
	COM_NUM		NUMBER			NOT NULL,
	COM_NAME	VARCHAR2(100)	NOT NULL,
	
	CONSTRAINT COMROOM_PK PRIMARY KEY(COM_NUM),
	CONSTRAINT COMROOM_UQ UNIQUE(COM_NAME)
	
);

CREATE TABLE COMBOARD(
	
	BOARD_NUM		NUMBER			NOT NULL,
	COM_NUM			NUMBER			NOT NULL,
	MEMBER_NUM		NUMBER			NOT NULL,
	BOARD_TITLE		VARCHAR2(200)	NOT NULL,
	MEMBER_ID		VARCHAR2(100)	NOT NULL,
	MEMBER_NICKNAME VARCHAR2(100)	NOT NULL,
	BOARD_CONTENT	VARCHAR2(4000)	NOT NULL,
	BOARD_DATE		DATE			NOT NULL,
	BOARD_TAG		VARCHAR2(1000),

	CONSTRAINT COMBOARD_PK PRIMARY KEY(BOARD_NUM),
	CONSTRAINT COMBOARD_FK FOREIGN KEY(COM_NUM) REFERENCES COMROOM(COM_NUM) ON DELETE CASCADE ENABLE
	
)

CREATE TABLE BOARDCOM(

	COMMENT_NUM		NUMBER			NOT NULL,
	BOARD_NUM		NUMBER			NOT NULL,
	COMMENT_GROUP	NUMBER			NOT NULL,
	MEMBER_NUM		NUMBER			NOT NULL,
	MEMBER_ID		VARCHAR2(100)	NOT NULL,
	MEMBER_NICKNAME VARCHAR2(100)	NOT NULL,
	COMMENT_CONTENT VARCHAR2(1000)	NOT NULL,
	COMMENT_DATE	DATE			NOT NULL,
	
	CONSTRAINT BOARDCOM_PK PRIMARY KEY(COMMENT_NUM),
	CONSTRAINT BOARDCOM_FK FOREIGN KEY(BOARD_NUM) REFERENCES COMBOARD(BOARD_NUM) ON DELETE CASCADE ENABLE

)

INSERT INTO COMROOM VALUES(COMROOM_SEQ.NEXTVAL, '자유게시판' );
INSERT INTO COMROOM VALUES(COMROOM_SEQ.NEXTVAL, '후기게시판' );
INSERT INTO COMROOM VALUES(COMROOM_SEQ.NEXTVAL, 'Q&A' );
SELECT COM_NUM, COM_NAME FROM COMROOM
