DROP SEQUENCE MEMBERSEQ;
DROP TABLE MEMBER;

CREATE SEQUENCE MEMBERSEQ;

CREATE TABLE MEMBER(
	MEMBER_NUM NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(100) UNIQUE,
	MEMBER_PW VARCHAR2(4000) NOT NULL,
	MEMBER_NAME VARCHAR2(100) NOT NULL,
	MEMBER_NICKNAME VARCHAR2(100) NOT NULL,
	MEMBER_ADDR VARCHAR2(1000) NOT NULL,
	MEMBER_PHONE VARCHAR2(300) NOT NULL,
	MEMBER_ROLE VARCHAR2(100) NOT NULL,
	MEMBER_ENABLED VARCHAR2(20) NOT NULL,
	MEMBER_GENDER VARCHAR2(10) NOT NULL,
	CONSTRAINT MEMBER_ENABLED_CHK CHECK(MEMBER_ENABLED IN ('Y', 'N'))
);

INSERT INTO MEMBER
VALUES(MEMBERSEQ.NEXTVAL, 'admin', 'admin1234', '봉가용', '관리자', '서울시 역삼동', '010-0000-0000', 'ADMIN', 'Y', 'HUMEN');

SELECT * FROM MEMBER
ORDER BY MEMBER_NUM DESC;